name: SneakyCharacterManager
version: 1.0.0
main: net.sneakycharactermanager.paper.SneakyCharacterManager
description: Paper/bungee plugin for switching characters in DvZ and LoM
author: Team Sneakymouse
website: https://rawb.tv
api-version: 1.19

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    GSit:
      load: AFTER
      required: true
